env:
  browser: true
  es2022: true
extends: standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0, 
  import/extensions: 0,
  semi: [2, "always"]
}
